### ISSUE TITLE
Look into if stellar-etl doesn't need to create a file when exporting data

### ISSUE THREAD

**Issue by acharb** [stellar/stellar-etl#128]
Part of the `stellar-etl-airflow` process is the `stellar-etl` exports data to a file on the pod's local storage, and then a shell script checks for data in the file before moving to a gcp folder. It's a little buggy where the gcp pods check to see if the file has data before moving it to another folder ([here](https://github.com/stellar/stellar-etl-airflow/blob/7d9fd4b836f0b205026759db418893cb3945e1a9/poststart.sh#L7)), and sometimes because of timing of when data is uploaded to the file the scripts incorrectly says the file is empty so doesn't move it.

I'm not sure if this is the best process we can do, to me it feels pretty convoluted, but if so then this ticket can be closed. But if we can not rely on uploading dat to an intermediary file or checking file sizes then I think we should.

Probably this is a better refactoring ticket, but adding this to track.

**Comment by sydneynotthecity** [comment]
This implementation is partly due to limitations in Google Cloud Composer. The `airflow-worker` is technically its own Docker image, so when we use our own Docker image in the `DockerOperator`, we are effectively executing a Docker image inside of a Docker image. 

One of the side effects of this implementation is we can only mount storage to a _new_ volume instead of mounting to an existing volume. Cloud composer has a `gcsfuse` mount that is shared across all `airflow-worker` pods (location is `/home/airflow/gcs/data`). This mount cannot be remounted in the `stellar-etl` Docker because it is already used, thus we have to write the file to a separate mount and then move it. 

It would be nice if we allowed `stellar-etl` to connect and write directly to Cloud Storage instead of a local file to circumvent this process. [Feature request](https://github.com/stellar/hubble/issues/199) to be prioritized; closing this issue
